---
-
  hosts: worker
  vars:
    db_user: dbusername
    db_name: dbname
    db_password: dbpassword
  tasks:
  - name: install dependencies for PostGreSQL
    apt: name={{ item }} update_cache=true state=latest
    with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  - name: install postgresql
    apt: name={{ item }} update_cache=true state=present
    with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2
  - name: Ensure the postgress service is running
    service: name=postgresql state=started enabled=yes
  - name: create the database which i have specifed in vars
    become: true
    become_user: postgres
    postgresql_db: name={{db_name}}
      template='template0'
      state=present
  - name: we need to provide access to the new database
    become: true
    become_user: postgres
    postgresql_user: db={{db_name}}
      name={{db_user}}
      password={{db_password}}
      priv=ALL
      state=present
