---
-
  hosts: worker
  tasks:
  - name: update and upgrade apt-packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #it will always check for update once in a day
  - name: install jdk 11
    apt:
      name: openjdk-11-jdk
      state: present
  
  - name: add tomcat group
    group:
      name: tomcat
  - name: add tomcat user
    user:
      name: tomcat
      group: tomcat
      home: /user/share/tomcat
      createhome: no 
  - name: create /opt/tomcat directory
    file: 
      path: /opt/tomcat
      state: directory
      mode: 0755
  - name: download the tomcat and unarchive
    unarchive:
      src: https://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.50/bin/apache-tomcat-9.0.50.tar.gz
      dest: /opt/tomcat
      remote_src: yes #it will download this package in all the machine
      extra_opts: [--strip-components=1]
  - name: change the ownership
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes 
      state: directory
